name = "builder-dev"
main = "builder-worker.js"
compatibility_date = "2026-02-12"

[env.production]
name = "builder-prod"

# Variables for the worker
[vars]
ENVIRONMENT = "development"
MAX_NOTEBOOKS = "4"
WORKER_COORDINATION = "true"
