# HEADY_BRAND:BEGIN
# HEADY SYSTEMS :: SACRED GEOMETRY
# FILE: packages/headyconnection-v13/.github/workflows/promptops.yml
# LAYER: root
# 
#         _   _  _____    _    ____   __   __
#        | | | || ____|  / \  |  _ \ \ \ / /
#        | |_| ||  _|   / _ \ | | | | \ V / 
#        |  _  || |___ / ___ \| |_| |  | |  
#        |_| |_||_____/_/   \_\____/   |_|  
# 
#    Sacred Geometry :: Organic Systems :: Breathing Interfaces
# HEADY_BRAND:END

name: PromptOps Governance
on:
  workflow_dispatch:
jobs:
  promptops:
    uses: heady-connection/governance/.github/workflows/promptops.yml@main
    secrets: inherit
